spring.application.name=m3_assistant

# ????????? ??? ?????????? ?? H2
spring.datasource.url=jdbc:h2:mem:m3db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ????????? Spring Boot ?????? ????????? ??????? ?? ?????? ????? Java-???????
spring.jpa.hibernate.ddl-auto=update

# ?????????? SQL-??????? ? ??????? IDEA (????? ?????? ??? ???????)
spring.jpa.show-sql=true